version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: create report folder
          command: |
             mkdir -p ~/work/cucumber
             touch ~/work/cucumber/report.txt
             echo "my testing notes" > ~/work/cucumber/report.html

      - store_artifacts:
          path: ~/work/cucumber
      - run:
              name: Send text report
              command: | 
                wget http://stedolan.github.io/jq/download/linux64/jq
                chmod +x ./jq
                cp jq /usr/bin
                
                reportLink=$(curl https://circleci.com/api/v1.1/project/github/${CIRCLE_USERNAME}/${CIRCLE_PROJECT_REPONAME}/${CIRCLE_BUILD_NUM}/artifacts?circle-token=${BuildReport} | jq -r '.[].url')
                echo "printing link"
                echo $reportLink
                curl -X POST -H 'Content-type: application/json' --data '{"text": "'${BUILD_REPORT_MESSAGE}'$reportLink'"}' ${SLACK_AUTOMATION_CHANNEL}