version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: create report folder
          command: |
             mkdir -p ~/work/cucumber
             pwd
             ls
             touch ~/work/cucumber
             pwd
             ls

      - store_artifacts:
          path: ~/work/cucumber