version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: create report folder
          command: |
             mkdir -p ~/work/cucumber
             touch ~/work/cucumber/report.txt
             echo "my testing notes" > ~/work/cucumber/report.html
#add comment
      - store_artifacts:
          path: ~/work/cucumber
      - run:
              name: Send text report
              environment:
                REPORT_MESSAGE: 'integration'
              command: |
                result="Build number: $CIRCLE_BUILD_NUM \n\n""Repo: $CIRCLE_REPOSITORY_URL \n\n""Commiter: $CIRCLE_PROJECT_USERNAME \n\n""Commit message: $(git log --format=oneline -n 1 $CIRCLE_SHA1)"
                COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
                echo "printing $COMMIT_MESSAGE"
                echo "printing $CIRCLE_BUILD_NUM"
                curl -X POST -H 'Content-type: application/json' --data '{"text": "Build number: '$CIRCLE_BUILD_NUM'\n\nRepo: '$CIRCLE_REPOSITORY_URL'\n\nCommiter:\t'$CIRCLE_PROJECT_USERNAME'\n\nCommit message: '"$COMMIT_MESSAGE"' "}' ${SLACK_AUTOMATION_CHANNEL}
