version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: create report folder
          command: |
             mkdir -p ~/work/cucumber
             pwd
             ls
             touch ~/work/cucumber/report.txt
             echo "my testing notes" > ~/work/cucumber/report.txt
             pwd
             ls
            

      - store_artifacts:
          path: ~/work/cucumber
      - run:
              name: Send text report
              command: |   
                TPATH = "this is a path"
                echo $TPATH
              command: > 
                 curl -X POST -H 'Content-type: application/json' --data 
                 '{"text":"This is a link "}' 
                 https://hooks.slack.com/services/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