version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: create report folder
          command: |
             mkdir -p ~/work/cucumber
             touch ~/work/cucumber/report.txt
             echo "my testing notes" > ~/work/cucumber/report.html

      - store_artifacts:
          path: ~/work/cucumber
      - run:
              name: Send text report
              command: | 
                wget http://stedolan.github.io/jq/download/linux64/jq
                chmod +x ./jq
                cp jq /usr/bin
                echo "jq is installed"
                reportLink=$(curl https://circleci.com/api/v1.1/project/github/qatutor/circle-ci-helloworld/66/artifacts?circle-token=$BuildReport | jq '.[].url')
                echo "printing link"
                echo $reportLink
                echo {"text":"$reportLink"}
                curl -X POST -H 'Content-type: application/json' --data '{"text":"$reportLink"}' https://hooks.slack.com/services/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