version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: create report folder
          command: |
             mkdir -p ~/work/cucumber
             touch ~/work/cucumber/report.txt
             echo "my testing notes" > ~/work/cucumber/report.html

      - store_artifacts:
          path: ~/work/cucumber
      - run:
              name: Send text report
              command: | 
                echo "request artifact"
                sudo apt-get install jq
                curl https://circleci.com/api/v1.1/project/github/qatutor/circle-ci-helloworld/66/artifacts?circle-token=80e9a8a99b6f02bfc5e12fcb108be9a341745d | jq '.[].url'

                