version: 2
jobs:
  build:
    docker:
      - image: gcc:8.1.0
    working_directory: ~/work
    steps:
      - checkout
      - run:
          name: create report folder
          command: |
             mkdir -p ~/work/cucumber
             touch ~/work/cucumber/report.txt
             echo "my testing notes" > ~/work/cucumber/report.html

      - store_artifacts:
          path: ~/work/cucumber
      - run:
              name: Send text report
              environment:
                TARGET_API: 'integration'
              command: | 
                # echo "Repo:"
                echo "Repo: $CIRCLE_REPOSITORY_URL"
                echo

                # echo "Commiter:"
                echo "Commiter: $CIRCLE_PROJECT_USERNAME"
                echo

                # echo "Commit message:"
                # COMMIT_MESSAGE=$(git log --format=oneline -n 1 $CIRCLE_SHA1)
                echo "Commit message: $(git log --format=oneline -n 1 $CIRCLE_SHA1)"

                # echo "Build number:"
                echo "Build number: $CIRCLE_BUILD_NUM"
                echo

                curl -X POST -H 'Content-type: application/json' --data '{"text": "'$CIRCLE_REPOSITORY_URL'"}' ${SLACK_AUTOMATION_CHANNEL}



          